<?php
// $Id$:


/**
 * Implementation of hook_perm().
 */
function multibooks_perm() {
  return array('edit secondary books');
}


/**
 * Implementation of hook_nodeapi().
 */
function multibooks_nodeapi(&$node, $op) {
  switch($op) {
    case 'update':
      _multibooks_update($node);
      break;
  }
}


/**
 * Implementation of hook_form_alter().
 */
function multibooks_form_alter(&$form, $form_state, $form_id) {
  if ((isset($form['#node'])) && ($form_id == $form['#node']->type . '_node_form')) {

    $options = array(0 => '<'. t('none') .'>');
    foreach (book_get_books() as $book) {
      $options[$book['nid']] = $book['title'];
    }
    $form['book']['secondary_book'] = array(
      '#type' => 'select',
      '#options' => $options,
      '#title' => t('Secondary book'),
      '#description' => t('Your page will also be a part of this book.'),
      '#weight' => 5
    );

    $form['book']['secondary_weight'] = array(
      '#type' => 'weight',
      '#title' => t('Secondary weight'),
      '#delta' => 15,
      '#weight' => 6,
      '#description' => t('Pages in secondary books are also ordered first by weight and then by title.'),
    );
  }
}


/**
 * Update menu links for the node in its secondary books.
 */
function _multibooks_update($node) {

  // Delete existing entries from the multibooks and menu_links tables
  db_query("DELETE FROM {multibooks} WHERE nid = %d", $node->nid);
  menu_link_delete(NULL, "node/{$node->nid}");

  // Add up-to-date entries
  db_query("INSERT INTO {multibooks} (nid, secondary_parent) VALUES(%d, %d)",
    $node->nid,
    $node->book['secondary_book'] 
  );
  $secondary_parent = node_load($node->book['secondary_book']);
  $menu_link = array(
    'link_title' => $node->title,
    'menu_name' => "book-toc-{$secondary_parent->nid}",
    'link_path' => "node/{$node->nid}",
    'router_path' => "node/%",
    'module' => "multibooks",
    'plid' => $secondary_parent->book['mlid'],
    'weight' => $secondary_parent->book['secondary_weight'],
  );
  menu_link_save($menu_link);
}
